### PR TITLE
Unit naming + front-end preview of original vs standard 

### PR DESCRIPTION
**Pull request by dave-mills**
This updates the front-end and export to show the unit name without any appended "-standardunit", so for e.g.: 
 - quintal
 - qunital-kg

...would both appear as "quintal" when presented to the user. This is a workaround as eventually we want a system where the user can convert more freely between unit types. 

This also includes the ability for users to toggle between viewing the original values and the converted values in the preview panel on the front-end (and adds a note to say both values are present in the download).

### CODE REVIEW

**Comment by ciara-mc** [comment]
Would it be possible to not display the message and the convert button if all values for that indicator have a conversion rate of 1?

I'm looking at some values where the unit doesn't change: 41.00 original and 41 standard, 5.50 original and 5.5 standard.
It would be nice to have the format of the standard as the original.

**Comment by dave-mills** [comment]
> Would it be possible to not display the message and the convert button if all values for that indicator have a conversion rate of 1?
Fixed so now values in the indicator preview pane are forced to show as 2dp. I think this works for now?

> I'm looking at some values where the unit doesn't change: 41.00 original and 41 standard, 5.50 original and 5.5 standard.
> It would be nice to have the format of the standard as the original.

Fixed so that the conversion option only shows if there are any conversion_rates that are not null and do not equal 1.

**Comment by ciara-mc** [comment]
Can the decimal places be dropped if there are zeros? Otherwise 2 is great

**Comment by dave-mills** [comment]
@ciara-mc sorry I totally missed your message about this merge conflict last week. I've fixed it up - see my latest commit. It was just that this and the other unit conversion branch involved editing some of the same functions, so we had to manually specify which lines from each branch to keep.

**Comment by dave-mills** [comment]
Just fixed the trailing zeros in the presentation of values and updated column headers when showing "converted" values. I think this is ready to merge.

**Comment by ciara-mc** [comment]
Values that have been converted are now not being rounded to 2dp.

I don't think "Converted Value" works as a column header as any values that were already in the standard unit will not have been converted.

The toggle state for the show original/standard button carries over when viewing different indicators. Would it be better to show the user the original values as default when they first view an indicator?

**Comment by dave-mills** [comment]
> Values that have been converted are now not being rounded to 2dp. 

Ah, good point. Level of precision to present is surprisingly tricky! 

> I don't think "Converted Value" works as a column header as any values that were already in the standard unit will not have been converted.

Fair. Does it work with just keeping "Value", given the "standardised unit" or "original unit" is in the next column? 


> The toggle state for the show original/standard button carries over when viewing different indicators. Would it be better to show the user the original values as default when they first view an indicator?

I think you're right here. I'll reset the boolean when the preview pane is closed.

**Comment by dave-mills** [comment]
In the indicator preview pane:
 - I've reset the value header to always be "Value". 
 - I've set a watcher to switch showConvertedValues back to false whenever the modal dialog is closed.

In IndicatorValue:
 - I've added rounding to the converted_value, so that it rounds to max 2dp. 

I hope this will do for now regarding rounding values? I think there's more we *could* do here - right now the rounding is pretty crude, as it doesn't account for the possibility that a value of "20.00" really is precise to 2dp, etc. But I think that particular rabbit hole is one we should avoid until people have started actually using the platform, and then perhaps we can have discussions with users and content experts about the precision of these calculated indicator values.

**Pull request merged**
